
build:
	docker-compose -f docker-compose.prod.yml build

up:
	mkdir -p data/
	rm -f data/.delete_me
	docker-compose -f docker-compose.prod.yml up

migrate:
	docker-compose -f docker-compose.prod.yml run web python manage.py makemigrations polls
	# docker-compose run web python manage.py sqlmigrate polls 0001
	docker-compose -f docker-compose.prod.yml run web python manage.py migrate

test:
	docker-compose -f docker-compose.prod.yml run web python manage.py test polls
